name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Download dependencies
        run: go mod tidy

      - name: Build
        run: go build ./...

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...
      
      - name: Run go run in all directories
        run: |
          set -e
          for dir in $(find . -type f -name "*.go" -exec dirname {} \; | sort -u); do
            echo ""
            echo "Running in $dir"
            cd $dir
            if [ -f "go.mod" ]; then
              go mod tidy
            fi
            go run .
            cd - > /dev/null
          done
